language: objective-c
osx_image: xcode8
before_install:
- pod repo update
script: xcodebuild -workspace "RealmBrowser.xcworkspace" -scheme "Realm Browser" test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
